/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package source;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author shweta
 */
public class RegForm extends javax.swing.JFrame {

    public static final int min_pwd = 8;
     public static final int max_pwd = 20;
    public RegForm() {
        initComponents();
        Toolkit t = Toolkit.getDefaultToolkit();
        Dimension d = t.getScreenSize();
        setSize(d.width, d.height);
        ButtonGroup bg = new ButtonGroup();
        bg.add(rbtnMale);
        bg.add(rbtnFemale);
        
//        set image on back button
        ImageIcon img = new ImageIcon("E:/Mtech project/Quiz/sign.png");
        SbtBtn.setIcon(img);
        ImageIcon img1 = new ImageIcon("E:/Mtech project/Quiz/goback.jpg");
        btnBack.setIcon(img1);
        ImageIcon img2 = new ImageIcon("E:/Mtech project/Quiz/reset2.jpg");
        rstBtn.setIcon(img2);
        ImageIcon img3 = new ImageIcon("E:/Mtech project/Quiz/signup.png");
        btn.setIcon(img3);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        pwd = new javax.swing.JPasswordField();
        Cpwd = new javax.swing.JPasswordField();
        SbtBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        rbtnMale = new javax.swing.JRadioButton();
        rbtnFemale = new javax.swing.JRadioButton();
        btnBack = new javax.swing.JButton();
        rstBtn = new javax.swing.JButton();
        btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register Yourself");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Name :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 120, 100, 34);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Email Id :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 300, 120, 34);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Password :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 380, 125, 35);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Confirm Password :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 470, 226, 34);

        tfName.setBackground(new java.awt.Color(204, 204, 255));
        tfName.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });
        getContentPane().add(tfName);
        tfName.setBounds(360, 120, 362, 40);

        tfEmail.setBackground(new java.awt.Color(204, 204, 255));
        tfEmail.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });
        getContentPane().add(tfEmail);
        tfEmail.setBounds(360, 290, 365, 40);

        pwd.setBackground(new java.awt.Color(204, 204, 255));
        pwd.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        getContentPane().add(pwd);
        pwd.setBounds(360, 380, 365, 40);

        Cpwd.setBackground(new java.awt.Color(204, 204, 255));
        Cpwd.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        Cpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CpwdActionPerformed(evt);
            }
        });
        getContentPane().add(Cpwd);
        Cpwd.setBounds(360, 470, 365, 40);

        SbtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SbtBtn);
        SbtBtn.setBounds(830, 360, 130, 40);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Gender :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 210, 110, 34);

        rbtnMale.setBackground(new java.awt.Color(204, 204, 255));
        rbtnMale.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        rbtnMale.setText("Male");
        rbtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMaleActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnMale);
        rbtnMale.setBounds(360, 210, 76, 39);

        rbtnFemale.setBackground(new java.awt.Color(204, 204, 255));
        rbtnFemale.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        rbtnFemale.setText("Female");
        getContentPane().add(rbtnFemale);
        rbtnFemale.setBounds(530, 210, 100, 39);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(840, 520, 130, 40);

        rstBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rstBtnActionPerformed(evt);
            }
        });
        getContentPane().add(rstBtn);
        rstBtn.setBounds(840, 440, 120, 50);

        btn.setText("jButton1");
        getContentPane().add(btn);
        btn.setBounds(310, 20, 430, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/form.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void SbtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtBtnActionPerformed
        try
        {
            String sn = tfName.getText();
            String gen = null;
            if(rbtnMale.isSelected())
            {
                gen = "Male";
                
            }
            else
            {
                gen = "Female";
            }
            String pass1 = String.valueOf(pwd.getPassword());
            String pass2 = String.valueOf(Cpwd.getPassword());
            String email = tfEmail.getText();
            
           
            
            
            
// validation code
            if(tfName.getText().trim().equals("")||
               rbtnMale.getText().equals("")||
               rbtnFemale.getText().equals("")||
               tfEmail.getText().equals("")||
               String.valueOf(pwd.getPassword()).equals("")||
               String.valueOf(Cpwd.getPassword()).equals(""))
            {
                JOptionPane.showMessageDialog(rootPane,"Please enter all the details :");
                return;
            }
            if(!(pass1.equals(pass2)))
            {
                JOptionPane.showMessageDialog(rootPane, "password did not matched, confirm it again!!!");
                return;
            }
            
//database connection
            Connection con1 = DriverManager.getConnection(DBConnect.con,DBConnect.user,DBConnect.pass);
            Statement st = con1.createStatement();
             
            String Query = "insert into Registration1 values('"+email+"','"+sn+"','"+gen+"','"+pass1+"');";
            int rows = st.executeUpdate(Query);
            JOptionPane.showMessageDialog(rootPane, "You Registration Completed successfully");
            
            con1.close();
            
            this.dispose();
            new NewJFrame().setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e.toString() );
        }
    }//GEN-LAST:event_SbtBtnActionPerformed

    private void CpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CpwdActionPerformed
        
    }//GEN-LAST:event_CpwdActionPerformed

    private void rstBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rstBtnActionPerformed
        tfName.setText("");
              rbtnMale.setSelected(false);
              rbtnFemale.setSelected(false);
               tfEmail.setText("");
               pwd.setText("");
               Cpwd.setText("");
               
    }//GEN-LAST:event_rstBtnActionPerformed

    private void rbtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMaleActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Cpwd;
    private javax.swing.JButton SbtBtn;
    private javax.swing.JButton btn;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale;
    private javax.swing.JButton rstBtn;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
