/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package source;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author shweta
 */
public class SelectSub extends javax.swing.JFrame {

    /**
     * Creates new form SelectSub
     */
    
    static String subject="";
    public SelectSub() {
        initComponents();
        Toolkit t = Toolkit.getDefaultToolkit();
        Dimension d = t.getScreenSize();
        setSize(d.width, d.height);
        ButtonGroup bg = new ButtonGroup();
        bg.add(rbtnC);
        bg.add(rbtnCPP);
        bg.add(rbtnJava);
        bg.add(rbtnJavaEE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnC = new javax.swing.JRadioButton();
        rbtnCPP = new javax.swing.JRadioButton();
        rbtnJava = new javax.swing.JRadioButton();
        rbtnJavaEE = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();
        btnResult = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        rbtnC.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        rbtnC.setForeground(new java.awt.Color(255, 255, 255));
        rbtnC.setText("C Programming");
        rbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCActionPerformed(evt);
            }
        });
        getContentPane().add(rbtnC);
        rbtnC.setBounds(370, 120, 197, 43);

        rbtnCPP.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        rbtnCPP.setForeground(new java.awt.Color(255, 255, 255));
        rbtnCPP.setText("C++");
        getContentPane().add(rbtnCPP);
        rbtnCPP.setBounds(370, 200, 197, 43);

        rbtnJava.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        rbtnJava.setForeground(new java.awt.Color(255, 255, 255));
        rbtnJava.setText("Java SE");
        getContentPane().add(rbtnJava);
        rbtnJava.setBounds(370, 270, 197, 43);

        rbtnJavaEE.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        rbtnJavaEE.setForeground(new java.awt.Color(255, 255, 255));
        rbtnJavaEE.setText("Java EE");
        getContentPane().add(rbtnJavaEE);
        rbtnJavaEE.setBounds(370, 340, 197, 43);

        jLabel1.setFont(new java.awt.Font("Snap ITC", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Select Subject To Play :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 40, 583, 67);

        btnPlay.setFont(new java.awt.Font("Snap ITC", 3, 36)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(102, 102, 0));
        btnPlay.setText("Play now :");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlay);
        btnPlay.setBounds(640, 420, 280, 50);

        btnResult.setFont(new java.awt.Font("Snap ITC", 3, 36)); // NOI18N
        btnResult.setForeground(new java.awt.Color(204, 0, 0));
        btnResult.setText("Check your result");
        btnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultActionPerformed(evt);
            }
        });
        getContentPane().add(btnResult);
        btnResult.setBounds(210, 520, 450, 55);

        btnBack.setFont(new java.awt.Font("Snap ITC", 3, 36)); // NOI18N
        btnBack.setForeground(new java.awt.Color(102, 102, 0));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(80, 420, 150, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/Q2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(1366, 768));
        jLabel2.setMinimumSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(4, 10, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCActionPerformed
       
                
                
            
        
    }//GEN-LAST:event_rbtnCActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        if(rbtnC.isSelected())
        {
            subject = "C Programming";
            new Questions().setVisible(true);
        }
        else if(rbtnCPP.isSelected())
        {
            subject = "CPP";
            new Questions().setVisible(true);
        }
        else if(rbtnJava.isSelected())
        {
            subject = "Java SE";
            new Questions().setVisible(true);
        }
        else if(rbtnJavaEE.isSelected())
        {
            subject = "Java EE";
            new Questions().setVisible(true);
        }
        else if(!(rbtnC.isSelected()||rbtnCPP.isSelected()||rbtnJava.isSelected()||rbtnJavaEE.isSelected()))
        {
            JOptionPane.showMessageDialog(rootPane, "Select Subject");
        }
        else
        {
            new Questions().setVisible(true);
        }
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultActionPerformed
         this.dispose();
        new Result().setVisible(true);
    }//GEN-LAST:event_btnResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectSub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rbtnC;
    private javax.swing.JRadioButton rbtnCPP;
    private javax.swing.JRadioButton rbtnJava;
    private javax.swing.JRadioButton rbtnJavaEE;
    // End of variables declaration//GEN-END:variables
}
